# dimensions
# in pixels
FULL_WIDTH = 300
FULL_HEIGHT = 216
DISPLAY_WIDTH = 288
DISPLAY_HEIGHT = 192
BLOCK_WIDTH = 6
BLOCK_HEIGHT = 12
# in blocks
FULL_WIDTH_BLOCKS = FULL_WIDTH // BLOCK_WIDTH
FULL_HEIGHT_BLOCKS = FULL_HEIGHT // BLOCK_HEIGHT
DISPLAY_WIDTH_BLOCKS = DISPLAY_WIDTH // BLOCK_WIDTH
DISPLAY_HEIGHT_BLOCKS = DISPLAY_HEIGHT // BLOCK_HEIGHT

# low level
PACKET_SIZE = 24
DATA_SIZE = 16
MINIMUM_PKT_SIZE = 6
MINIMUM_SCROLL_SIZE = 3
HEADER_SIZE = 8
PALETTE_SIZE = 16

PACKETS_PER_SECOND = 300

# magic numbers
CDG_COMMAND_MAGIC_BYTE = 0x09
INST_PRESET_MEMORY = 1
INST_PRESET_BORDER = 2
INST_WRITE_FONT_BLOCK = 6
INST_SCROLL_PRESET = 20
INST_SCROLL_COPY = 24
INST_DEFINE_TRANSP_COLOR = 28
INST_LOAD_COLOR_TABLE_LOW = 30
INST_LOAD_COLOR_TABLE_HIGH = 31
INST_XOR_FONT_BLOCK = 38
