
FULL_WIDTH = 300
FULL_HEIGHT = 216
DISPLAY_WIDTH = 294
DISPLAY_HEIGHT = 204
BORDER_WIDTH = 6
BORDER_HEIGHT = 12

CDG_COMMAND_MAGIC_BYTE = 0x09
MASK = 0x3F

INST_PRESET_MEMORY = 1
INST_PRESET_BORDER = 2
INST_WRITE_FONT_BLOCK = 6
INST_SCROLL_PRESET = 20
INST_SCROLL_COPY = 24
INST_DEFINE_TRANSP_COLOR = 28
INST_LOAD_COLOR_TABLE_LOW = 30
INST_LOAD_COLOR_TABLE_HIGH = 31
INST_XOR_FONT_BLOCK = 38

PACKET_SIZE = 24
DATA_SIZE = 16
TILE_HEIGHT = 12
TILE_WIDTH = 6
MINIMUM_PKT_SIZE = 6
MINIMUM_SCROLL_SIZE = 3
HEADER_SIZE = 8
PALETTE_SIZE = 16
